# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.projected_customer_charge_shipment_create import ProjectedCustomerChargeShipmentCreate  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectedCustomerChargeShipmentCreate(unittest.TestCase):
    """ProjectedCustomerChargeShipmentCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectedCustomerChargeShipmentCreate(self):
        """Test ProjectedCustomerChargeShipmentCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.projected_customer_charge_shipment_create.ProjectedCustomerChargeShipmentCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
