# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.shipper_invoice_item_get_read import ShipperInvoiceItemGetRead  # noqa: E501
from swagger_client.rest import ApiException


class TestShipperInvoiceItemGetRead(unittest.TestCase):
    """ShipperInvoiceItemGetRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShipperInvoiceItemGetRead(self):
        """Test ShipperInvoiceItemGetRead"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.shipper_invoice_item_get_read.ShipperInvoiceItemGetRead()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
