# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.one_of_shipment_booking_v2_jsonld_shipment_booking_create_context import OneOfShipmentBookingV2JsonldShipmentBookingCreateContext  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfShipmentBookingV2JsonldShipmentBookingCreateContext(unittest.TestCase):
    """OneOfShipmentBookingV2JsonldShipmentBookingCreateContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfShipmentBookingV2JsonldShipmentBookingCreateContext(self):
        """Test OneOfShipmentBookingV2JsonldShipmentBookingCreateContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_shipment_booking_v2_jsonld_shipment_booking_create_context.OneOfShipmentBookingV2JsonldShipmentBookingCreateContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
