# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.shipment_booking_v2_shipment_booking_created_jsonld import ShipmentBookingV2ShipmentBookingCreatedJsonld  # noqa: E501
from swagger_client.rest import ApiException


class TestShipmentBookingV2ShipmentBookingCreatedJsonld(unittest.TestCase):
    """ShipmentBookingV2ShipmentBookingCreatedJsonld unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShipmentBookingV2ShipmentBookingCreatedJsonld(self):
        """Test ShipmentBookingV2ShipmentBookingCreatedJsonld"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.shipment_booking_v2_shipment_booking_created_jsonld.ShipmentBookingV2ShipmentBookingCreatedJsonld()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
