# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.one_of_shipment_v2_shipment_created_jsonld_context import OneOfShipmentV2ShipmentCreatedJsonldContext  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfShipmentV2ShipmentCreatedJsonldContext(unittest.TestCase):
    """OneOfShipmentV2ShipmentCreatedJsonldContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfShipmentV2ShipmentCreatedJsonldContext(self):
        """Test OneOfShipmentV2ShipmentCreatedJsonldContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_shipment_v2_shipment_created_jsonld_context.OneOfShipmentV2ShipmentCreatedJsonldContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
