# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideAPI.authenticate_api import AuthenticateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthenticateApi(unittest.TestCase):
    """AuthenticateApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_credentials_item(self):
        """Test case for post_credentials_item

        Authenticate to start session.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
