# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.any_of_book_shipment_jsonld_team_book_shipment_create_delivery import AnyOfBookShipmentJsonldTeamBookShipmentCreateDelivery  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfBookShipmentJsonldTeamBookShipmentCreateDelivery(unittest.TestCase):
    """AnyOfBookShipmentJsonldTeamBookShipmentCreateDelivery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfBookShipmentJsonldTeamBookShipmentCreateDelivery(self):
        """Test AnyOfBookShipmentJsonldTeamBookShipmentCreateDelivery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_of_book_shipment_jsonld_team_book_shipment_create_delivery.AnyOfBookShipmentJsonldTeamBookShipmentCreateDelivery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
