# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.one_of_get_accessorials_jsonld_context import OneOfGetAccessorialsJsonldContext  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfGetAccessorialsJsonldContext(unittest.TestCase):
    """OneOfGetAccessorialsJsonldContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfGetAccessorialsJsonldContext(self):
        """Test OneOfGetAccessorialsJsonldContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_get_accessorials_jsonld_context.OneOfGetAccessorialsJsonldContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
