# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.any_of_shipment_v2_shipment_jsonld_shipment_create_bill_to import AnyOfShipmentV2ShipmentJsonldShipmentCreateBillTo  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfShipmentV2ShipmentJsonldShipmentCreateBillTo(unittest.TestCase):
    """AnyOfShipmentV2ShipmentJsonldShipmentCreateBillTo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfShipmentV2ShipmentJsonldShipmentCreateBillTo(self):
        """Test AnyOfShipmentV2ShipmentJsonldShipmentCreateBillTo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_of_shipment_v2_shipment_jsonld_shipment_create_bill_to.AnyOfShipmentV2ShipmentJsonldShipmentCreateBillTo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
