# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.bill_to_jsonld_invoice_item_get_read import BillToJsonldInvoiceItemGetRead  # noqa: E501
from swagger_client.rest import ApiException


class TestBillToJsonldInvoiceItemGetRead(unittest.TestCase):
    """BillToJsonldInvoiceItemGetRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillToJsonldInvoiceItemGetRead(self):
        """Test BillToJsonldInvoiceItemGetRead"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bill_to_jsonld_invoice_item_get_read.BillToJsonldInvoiceItemGetRead()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
