# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideModel.one_of_projected_expense_jsonld_shipment_booking_create_context import OneOfProjectedExpenseJsonldShipmentBookingCreateContext  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfProjectedExpenseJsonldShipmentBookingCreateContext(unittest.TestCase):
    """OneOfProjectedExpenseJsonldShipmentBookingCreateContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfProjectedExpenseJsonldShipmentBookingCreateContext(self):
        """Test OneOfProjectedExpenseJsonldShipmentBookingCreateContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_projected_expense_jsonld_shipment_booking_create_context.OneOfProjectedExpenseJsonldShipmentBookingCreateContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
