# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.TeamWorldwideAPI.shipment_v2_api import ShipmentV2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestShipmentV2Api(unittest.TestCase):
    """ShipmentV2Api unit test stubs"""

    def setUp(self):
        self.api = ShipmentV2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_get_shipment_status_collection(self):
        """Test case for get_get_shipment_status_collection

        Gets the shipment status by house bill.  # noqa: E501
        """
        pass

    def test_get_house_bill_get_house_bill_collection(self):
        """Test case for get_house_bill_get_house_bill_collection

        Gets and Reserves a Team WorldWide HouseBill.  # noqa: E501
        """
        pass

    def test_post_create_shipment_booking_shipment_booking_v2_collection(self):
        """Test case for post_create_shipment_booking_shipment_booking_v2_collection

        Book shipments to Team Worldwide.  # noqa: E501
        """
        pass

    def test_post_create_shipment_shipment_v2_collection(self):
        """Test case for post_create_shipment_shipment_v2_collection

        Book a single shipment to Team Worldwide.  # noqa: E501
        """
        pass

    def test_put_add_new_shipment_note_shipment_note_resource_item(self):
        """Test case for put_add_new_shipment_note_shipment_note_resource_item

        Add Shipment Note.  # noqa: E501
        """
        pass

    def test_put_update_team_booking_update_team_booking_item(self):
        """Test case for put_update_team_booking_update_team_booking_item

        Update Booking.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
