# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BrokerInformationTeamBookShipmentCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'contact': 'str',
        'phone': 'str',
        'notes': 'str',
        'customs_value': 'str'
    }

    attribute_map = {
        'name': 'name',
        'contact': 'contact',
        'phone': 'phone',
        'notes': 'notes',
        'customs_value': 'customsValue'
    }

    def __init__(self, name=None, contact=None, phone=None, notes=None, customs_value=None):  # noqa: E501
        """BrokerInformationTeamBookShipmentCreate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._contact = None
        self._phone = None
        self._notes = None
        self._customs_value = None
        self.discriminator = None
        self.name = name
        self.contact = contact
        self.phone = phone
        if notes is not None:
            self.notes = notes
        if customs_value is not None:
            self.customs_value = customs_value

    @property
    def name(self):
        """Gets the name of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501


        :return: The name of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BrokerInformationTeamBookShipmentCreate.


        :param name: The name of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def contact(self):
        """Gets the contact of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501


        :return: The contact of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :rtype: str
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this BrokerInformationTeamBookShipmentCreate.


        :param contact: The contact of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :type: str
        """
        if contact is None:
            raise ValueError("Invalid value for `contact`, must not be `None`")  # noqa: E501

        self._contact = contact

    @property
    def phone(self):
        """Gets the phone of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501


        :return: The phone of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this BrokerInformationTeamBookShipmentCreate.


        :param phone: The phone of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :type: str
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone

    @property
    def notes(self):
        """Gets the notes of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501


        :return: The notes of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this BrokerInformationTeamBookShipmentCreate.


        :param notes: The notes of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :type: str
        """

        self._notes = notes

    @property
    def customs_value(self):
        """Gets the customs_value of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501


        :return: The customs_value of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :rtype: str
        """
        return self._customs_value

    @customs_value.setter
    def customs_value(self, customs_value):
        """Sets the customs_value of this BrokerInformationTeamBookShipmentCreate.


        :param customs_value: The customs_value of this BrokerInformationTeamBookShipmentCreate.  # noqa: E501
        :type: str
        """

        self._customs_value = customs_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BrokerInformationTeamBookShipmentCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrokerInformationTeamBookShipmentCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
