# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InvoiceDetailJsonldInvoiceItemGetRead(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context': 'OneOfInvoiceDetailJsonldInvoiceItemGetReadContext',
        'id': 'str',
        'type': 'str',
        'charge_code': 'str',
        'description': 'str',
        'charge': 'float',
        'amount': 'str'
    }

    attribute_map = {
        'context': '@context',
        'id': '@id',
        'type': '@type',
        'charge_code': 'chargeCode',
        'description': 'description',
        'charge': 'charge',
        'amount': 'amount'
    }

    def __init__(self, context=None, id=None, type=None, charge_code=None, description=None, charge=None, amount=None):  # noqa: E501
        """InvoiceDetailJsonldInvoiceItemGetRead - a model defined in Swagger"""  # noqa: E501
        self._context = None
        self._id = None
        self._type = None
        self._charge_code = None
        self._description = None
        self._charge = None
        self._amount = None
        self.discriminator = None
        if context is not None:
            self.context = context
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if charge_code is not None:
            self.charge_code = charge_code
        if description is not None:
            self.description = description
        if charge is not None:
            self.charge = charge
        if amount is not None:
            self.amount = amount

    @property
    def context(self):
        """Gets the context of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501


        :return: The context of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :rtype: OneOfInvoiceDetailJsonldInvoiceItemGetReadContext
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this InvoiceDetailJsonldInvoiceItemGetRead.


        :param context: The context of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :type: OneOfInvoiceDetailJsonldInvoiceItemGetReadContext
        """

        self._context = context

    @property
    def id(self):
        """Gets the id of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501


        :return: The id of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InvoiceDetailJsonldInvoiceItemGetRead.


        :param id: The id of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501


        :return: The type of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InvoiceDetailJsonldInvoiceItemGetRead.


        :param type: The type of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def charge_code(self):
        """Gets the charge_code of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501


        :return: The charge_code of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :rtype: str
        """
        return self._charge_code

    @charge_code.setter
    def charge_code(self, charge_code):
        """Sets the charge_code of this InvoiceDetailJsonldInvoiceItemGetRead.


        :param charge_code: The charge_code of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :type: str
        """

        self._charge_code = charge_code

    @property
    def description(self):
        """Gets the description of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501


        :return: The description of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InvoiceDetailJsonldInvoiceItemGetRead.


        :param description: The description of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def charge(self):
        """Gets the charge of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501


        :return: The charge of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :rtype: float
        """
        return self._charge

    @charge.setter
    def charge(self, charge):
        """Sets the charge of this InvoiceDetailJsonldInvoiceItemGetRead.


        :param charge: The charge of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :type: float
        """

        self._charge = charge

    @property
    def amount(self):
        """Gets the amount of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501


        :return: The amount of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InvoiceDetailJsonldInvoiceItemGetRead.


        :param amount: The amount of this InvoiceDetailJsonldInvoiceItemGetRead.  # noqa: E501
        :type: str
        """

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvoiceDetailJsonldInvoiceItemGetRead, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoiceDetailJsonldInvoiceItemGetRead):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
