# coding: utf-8

"""
    Team Worldwide API 2022

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShipmentV2ShipmentCreated(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_id': 'str',
        'shipment_key': 'int',
        'house_bill': 'str',
        'pickup_date_as_readable': 'str',
        'pickup_date': 'datetime',
        'reference_numbers': 'list[str]'
    }

    attribute_map = {
        'unique_id': 'uniqueId',
        'shipment_key': 'shipmentKey',
        'house_bill': 'houseBill',
        'pickup_date_as_readable': 'pickupDateAsReadable',
        'pickup_date': 'pickupDate',
        'reference_numbers': 'referenceNumbers'
    }

    def __init__(self, unique_id=None, shipment_key=None, house_bill=None, pickup_date_as_readable=None, pickup_date=None, reference_numbers=None):  # noqa: E501
        """ShipmentV2ShipmentCreated - a model defined in Swagger"""  # noqa: E501
        self._unique_id = None
        self._shipment_key = None
        self._house_bill = None
        self._pickup_date_as_readable = None
        self._pickup_date = None
        self._reference_numbers = None
        self.discriminator = None
        if unique_id is not None:
            self.unique_id = unique_id
        if shipment_key is not None:
            self.shipment_key = shipment_key
        if house_bill is not None:
            self.house_bill = house_bill
        if pickup_date_as_readable is not None:
            self.pickup_date_as_readable = pickup_date_as_readable
        if pickup_date is not None:
            self.pickup_date = pickup_date
        if reference_numbers is not None:
            self.reference_numbers = reference_numbers

    @property
    def unique_id(self):
        """Gets the unique_id of this ShipmentV2ShipmentCreated.  # noqa: E501


        :return: The unique_id of this ShipmentV2ShipmentCreated.  # noqa: E501
        :rtype: str
        """
        return self._unique_id

    @unique_id.setter
    def unique_id(self, unique_id):
        """Sets the unique_id of this ShipmentV2ShipmentCreated.


        :param unique_id: The unique_id of this ShipmentV2ShipmentCreated.  # noqa: E501
        :type: str
        """

        self._unique_id = unique_id

    @property
    def shipment_key(self):
        """Gets the shipment_key of this ShipmentV2ShipmentCreated.  # noqa: E501


        :return: The shipment_key of this ShipmentV2ShipmentCreated.  # noqa: E501
        :rtype: int
        """
        return self._shipment_key

    @shipment_key.setter
    def shipment_key(self, shipment_key):
        """Sets the shipment_key of this ShipmentV2ShipmentCreated.


        :param shipment_key: The shipment_key of this ShipmentV2ShipmentCreated.  # noqa: E501
        :type: int
        """

        self._shipment_key = shipment_key

    @property
    def house_bill(self):
        """Gets the house_bill of this ShipmentV2ShipmentCreated.  # noqa: E501


        :return: The house_bill of this ShipmentV2ShipmentCreated.  # noqa: E501
        :rtype: str
        """
        return self._house_bill

    @house_bill.setter
    def house_bill(self, house_bill):
        """Sets the house_bill of this ShipmentV2ShipmentCreated.


        :param house_bill: The house_bill of this ShipmentV2ShipmentCreated.  # noqa: E501
        :type: str
        """

        self._house_bill = house_bill

    @property
    def pickup_date_as_readable(self):
        """Gets the pickup_date_as_readable of this ShipmentV2ShipmentCreated.  # noqa: E501


        :return: The pickup_date_as_readable of this ShipmentV2ShipmentCreated.  # noqa: E501
        :rtype: str
        """
        return self._pickup_date_as_readable

    @pickup_date_as_readable.setter
    def pickup_date_as_readable(self, pickup_date_as_readable):
        """Sets the pickup_date_as_readable of this ShipmentV2ShipmentCreated.


        :param pickup_date_as_readable: The pickup_date_as_readable of this ShipmentV2ShipmentCreated.  # noqa: E501
        :type: str
        """

        self._pickup_date_as_readable = pickup_date_as_readable

    @property
    def pickup_date(self):
        """Gets the pickup_date of this ShipmentV2ShipmentCreated.  # noqa: E501


        :return: The pickup_date of this ShipmentV2ShipmentCreated.  # noqa: E501
        :rtype: datetime
        """
        return self._pickup_date

    @pickup_date.setter
    def pickup_date(self, pickup_date):
        """Sets the pickup_date of this ShipmentV2ShipmentCreated.


        :param pickup_date: The pickup_date of this ShipmentV2ShipmentCreated.  # noqa: E501
        :type: datetime
        """

        self._pickup_date = pickup_date

    @property
    def reference_numbers(self):
        """Gets the reference_numbers of this ShipmentV2ShipmentCreated.  # noqa: E501


        :return: The reference_numbers of this ShipmentV2ShipmentCreated.  # noqa: E501
        :rtype: list[str]
        """
        return self._reference_numbers

    @reference_numbers.setter
    def reference_numbers(self, reference_numbers):
        """Sets the reference_numbers of this ShipmentV2ShipmentCreated.


        :param reference_numbers: The reference_numbers of this ShipmentV2ShipmentCreated.  # noqa: E501
        :type: list[str]
        """

        self._reference_numbers = reference_numbers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShipmentV2ShipmentCreated, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShipmentV2ShipmentCreated):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
